name:                quoted-prettyprinter
version:             0.1.1
github:              dcastrop/QPretty
license:             BSD3
author:              David Castro-Perez<david.castro.dcp@gmail.com>
maintainer:          David Castro-Perez<david.castro.dcp@gmail.com>
copyright:           2017 David Castro-Perez

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Quoted Pretty Printing utility for Haskell
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/dcastrop/QPretty#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell >= 2.14 && < 2.15
- haskell-src-meta > 0.8 && < 0.9
- prettyprinter > 1.2 && < 1.3
- syb > 0.6 && < 0.8
- parsec > 3.0 && < 3.2

library:
  source-dirs: src
  exposed-modules: Data.Text.Prettyprint.EDoc
  ghc-options:
  - -Wall
  - -Werror

tests:
  QPretty-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - quoted-prettyprint
